apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-maven
spec:
  inputs:
    resources:
      - name: source
        type: git
    # params:
    #   - name: directory
    #     description: Working directory parameter
    #     default: /workspace/workspace
  outputs:
    resources:
      - name: source
        type: git
  steps:
    - name: maven-build
      image: maven:3.6.3-jdk-8-slim
      workingDir: /workspace/source
      # workingDir: ${inputs.params.directory}
      command: ["mvn"]
      args:
        - "clean"
        - "install"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-oc
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: directory
        description: Working directory parameter
        default: /workspace/source/deploy-manifest
      - name: deployFile
        description: Deployment file for app
        default: test-deploy.yaml
  steps:
    - name: oc-deploy
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source/deploy-manifest
      # workingDir: "${inputs.params.directory}"
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifests in $(inputs.params.deployFile) directory
          oc apply -f $(inputs.params.deployFile)
          echo -----------------------------------
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: petclinic-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: container-image
      type: image
  # params:
  #   - name: 
  #     description: 
  #     default: 
  tasks:
    # - name: petclinic-maven
    #   taskRef:
    #     name: build-maven
    #   # params:
    #   #   - name: 
    #   #     value: 
    #   resources:
    #     inputs:
    #       - name: source
    #         resource: source-repo
    #     outputs:
    #       - name: source
    #         resource: source-repo
    - name: petclinic-buildah
      taskRef:
        name: buildah-test
        # kind: ClusterTask
      resources:
        inputs:
          - name: source
            resource: source-repo
            # from: 
            #   - petclinic-maven
        outputs:
          - name: image
            resource: container-image
      params:
      - name: TLSVERIFY
        value: "false"
      - name: DOCKERFILE
        value: "multistage.Dockerfile"
      - name: BUILDER_IMAGE
        value: quay.io/buildah/stable:v1.14.0
    - name: petclinic-deploy
      taskRef:
        name: deploy-oc
      runAfter:
        - petclinic-buildah
      resources:
        inputs:
          - name: source
            resource: source-repo
      params:
        - name: deployFile
          value: test-deploy.yaml