apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: petclinic-deploy-taskrun
spec:
  taskRef:
    name: deploy-oc
  inputs:
    resources:
      - name: workspacedeploy
        resourceRef:
          name: petclinic-git
    params:
      - name: deployFile
        value: test-deploy.yaml
      
